### ISSUE TITLE
[BUG] unknown error

### ISSUE THREAD

**Issue by rosekick** [olokos/Surftimer-olokos#111]
**Describe the bug**
CPrintToChat SkillGroup endlessly (happens randomly)

**Screenshots**
https://imgur.com/a/AzMZuFG
https://pastebin.com/Ywgejqmn

**Plugin List**
latest dev version

**Additional context**
no errors in console,no errors in logs file
it happen randomly  just right after player join server 
i delete "SkillGroup" phrase because it make me sick

**Comment by rosekick** [comment]
btw,my SkillGroup changed all "rank" to "points"

**Comment by olokos** [comment]
Well, you removed an important line of code, what did you expect, really?😄

**Comment by rosekick** [comment]
> Well, you removed an important line of code, what did you expect, really?😄

pay attention to the error timetable

**Comment by olokos** [comment]
@rosekick 
`L 05/09/2020 - 12:59:14: [SM] Exception reported: Language phrase "SkillGroup" not found (arg 4)`

That's the problem here

**Comment by TheGunter24** [comment]
could you try the default configuration ?
download [dev repo](https://github.com/olokos/Surftimer-olokos/archive/dev.zip), download [required](https://github.com/olokos/Surftimer-olokos#requirements) and compile it.
check if you'r skillgroup chat spam still occours
