### ISSUE TITLE
[BUG] I can't compile it

### ISSUE THREAD

**Issue by edyedyy** [olokos/Surftimer-olokos#113]
why i recive this error? I'm too dumb to compile it?
SurfTimer.sp(26) : fatal error 183: cannot read from file: "discord"

**Comment by LubricantJam** [comment]
Question; why are you trying to compile? Also, you're missing the includes.

**Comment by Bara** [comment]
You need the includes files from [Discord-API](https://github.com/Deathknife/sourcemod-discord/tree/master/include).
