### ISSUE TITLE
[BUG] Stage ranking doesn't display sometimes

### ISSUE THREAD

**Issue by Sarrus1** [olokos/Surftimer-olokos#115]
**Bug description:**
The stage ranking doesn't display sometimes, when a player completes a stage.
Checkout the video.

**Expected behavior:**
The stage ranking should consistently be displayed when a player completes a stage.

**Video:**
[https://www.youtube.com/watch?v=jcMsm7yfO9A&feature=youtu.be](url)

**Plugin List:**
- Surftimer v285
- !ws plugin
- sourcemods base plugins

**Comment by dPexxIAM** [comment]
I watched the video, can't see anything wrong. I think you're confused since you are not improving on every stage. there-for don't get the new rank print like: Rank X/X

**Comment by Sarrus1** [comment]
Ah I see, I didn't know it worked like that, thanks a lot!
