### ISSUE TITLE
Database error[BUG]

### ISSUE THREAD

**Issue by Spry-T** [olokos/Surftimer-olokos#118]
[SM] Exception reported: [SurfTimer] Database tables could not be created! Error: Lost connection to MySQL server during query
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] SetFailState
[SM]   [1] Line 117, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed

**Comment by Bara** [comment]
Duplicate: https://github.com/olokos/Surftimer-olokos/issues/62
