### ISSUE TITLE
[BUG] Array-based enum structs needs to be converted to fully support SM 1.11

### ISSUE THREAD

**Issue by olokos** [olokos/Surftimer-olokos#14]
`// SurfTimer.sp(367) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// SurfTimer.sp(1383) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2307) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2415) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2474) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/misc.sp(2505) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/sql.sp(1780) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/commands.sp(2055) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(881) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(898) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
// surftimer/replay.sp(913) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs`

**Describe the bug**
Array-based enum structs are very weird and it's good that they are fazed out, yet we're still using them in surftimer.

**Expected behavior**
We shouldn't get any warnings during compilation time and there should be no issues with SM1.11 once this is resolved.

**Additional context**
@ESK0  has tried to resolve this bug, but when I tried merging his code, there were other bugs and issues, nonetheless the idea is very good.
f5db512
and
845f764

**Comment by Bara** [comment]
I already work on this 👍

**Comment by ESK0** [comment]
The only issue I had was loading records from file.. Dunno why its saved in text file.
