### ISSUE TITLE
[BUG]Bot replays sometimes will cause the entire server to crash

### ISSUE THREAD

**Issue by olokos** [olokos/Surftimer-olokos#15]
**Describe the bug**
`Bad SetLocalOrigin(1668667682221316898816.000000,0.000000,0.000000) on TQnder.ZiP (01:48:21)
Net channel ratelimit exceeded for 80.208.156.231:27005: 415 packets rejected.
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,0.000000,451597895708723242850116356276224.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,811949673539110778783662080.000000,0.000000) on Baljeeter (00:06:82)
L 04/15/2020 - 23:39:46: [SM] Exception reported: Script execution timed out
L 04/15/2020 - 23:39:46: [SM] Blaming: SurfTimer.smx
L 04/15/2020 - 23:39:46: [SM] Call stack trace:
L 04/15/2020 - 23:39:46: [SM]   [1] Line 1129, surftimer/hooks.sp::OnPlayerRunCmd
Net channel ratelimit exceeded for 80.208.156.231:27005: 397 packets rejected.
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(287340736.000000,0.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(287340736.000000,0.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
Bad SetLocalAngles(0.000000,287340736.000000,0.000000) on TQnder.ZiP (01:48:21)
ace: try deleting the replay
Bad SetLocalAngles(0.000000,4599452368342004650737664.000000,0.000000) on Baljeeter (00:06:82)`

**Expected behavior**
Bots should work

**Additional context**
Somehow bot replays gets bugged, a workaround is to delete a glitched record replay, but it should not happen in the first place.

**Comment by 13ace37** [comment]
> Just set
sv_holiday_mode "0" in config

**Comment by olokos** [comment]
Wut? Could you give me some insight into this? Haven't heard about this before :open_mouth:

**Comment by 13ace37** [comment]
https://forums.alliedmods.net/showthread.php?t=311562

**Comment by sneak-it** [comment]
@olokos Has this fixed your issue?

**Comment by olokos** [comment]
Yes, like with a magic wand, not sure how much was it the command and how much recent commits, but I haven't seen this bug for a month now, which is awesome.
