### ISSUE TITLE
[BUG] getting various types of bugs and server crashes too

### ISSUE THREAD

**Issue by akazetaa** [olokos/Surftimer-olokos#17]
**Describe the bug**
I am getting these "Exception reported" in my Sourcemod logs, and I don't know which one of these is crashing my server, I had fluffy's Surftimer with the same plugins that I have right now, same version of SM and MM.

`L 04/15/2020 - 01:16:53: [SM] Exception reported: Failed to grow array`
`L 04/15/2020 - 01:16:53: [SM] Blaming: SurfTimer.smx`
`L 04/15/2020 - 01:16:53: [SM] Call stack trace:`
`L 04/15/2020 - 01:16:53: [SM]   [0] PushArrayArray`
`L 04/15/2020 - 01:16:53: [SM]   [1] Line 920, surftimer/replay.sp::RecordReplay`
`L 04/15/2020 - 01:16:53: [SM]   [2] Line 1109, surftimer/hooks.sp::OnPlayerRunCmd`

`L 04/15/2020 - 01:58:30: [SM] Exception reported: Array index out-of-bounds (index -1, limit 128)`
`L 04/15/2020 - 01:58:30: [SM] Blaming: SurfTimer.smx`
`L 04/15/2020 - 01:58:30: [SM] Call stack trace:`
`L 04/15/2020 - 01:58:30: [SM]   [1] Line 393, surftimer/misc.sp::setClientLocation`
`L 04/15/2020 - 01:58:30: [SM]   [2] Line 180, surftimer/hooks.sp::Event_OnPlayerSpawn`
`L 04/15/2020 - 01:58:30: [SM]   [4] ChangeClientTeam`
`L 04/15/2020 - 01:58:30: [SM]   [5] Line 571, surftimer/misc.sp::TeamChangeActual`
`L 04/15/2020 - 01:58:30: [SM]   [6] Line 1375, surftimer/commands.sp::Command_JoinTeam`

`L 04/15/2020 - 13:41:53: [SM] Exception reported: Array index out-of-bounds (index 89, limit 37)`
`L 04/15/2020 - 13:41:53: [SM] Blaming: SurfTimer.smx`
`L 04/15/2020 - 13:41:53: [SM] Call stack trace:`
`L 04/15/2020 - 13:41:53: [SM]   [1] Line 204, surftimer/misc.sp::teleportClient`
`L 04/15/2020 - 13:41:53: [SM]   [2] Line 985, surftimer/commands.sp::Command_ToStage`

`L 04/14/2020 - 04:39:10: [SM] Exception reported: Entity 6 (6) is invalid`
`L 04/14/2020 - 04:39:10: [SM] Blaming: SurfTimer.smx`
`L 04/14/2020 - 04:39:10: [SM] Call stack trace:`
`L 04/14/2020 - 04:39:10: [SM]   [0] GetEntPropVector`
`L 04/14/2020 - 04:39:10: [SM]   [1] Line 1429, surftimer/hooks.sp::DelayedVelocityCap`

`L 04/14/2020 - 05:03:48: [SM] Exception reported: Client 18 is not in game`
`L 04/14/2020 - 05:03:48: [SM] Blaming: SurfTimer.smx`
`L 04/14/2020 - 05:03:48: [SM] Call stack trace:`
`L 04/14/2020 - 05:03:48: [SM]   [0] ThrowError`
`L 04/14/2020 - 05:03:48: [SM]   [1] Line 88, C:\Users\Roberto\Desktop\scripting\include\colorvariables.inc::CPrintToChat`
`L 04/14/2020 - 05:03:48: [SM]   [2] Line 3998, surftimer/misc.sp::StyleFinishedMsgs`
`L 04/14/2020 - 05:03:48: [SM]   [3] Line 6845, surftimer/sql.sp::SQL_UpdateStyleRecordCallback2`

**Expected behavior**
I expect to get my server running with no crashes, I don't know what causes those errors, I just got a lot of messages from the players that play in the server saying that it is crashing a lot.

**Comment by olokos** [comment]
Are u using SM1.11 by any chance?
Possibly #16 can help with those, rough guess.

**Comment by akazetaa** [comment]
SourceMod Version: 1.10.0.6482
Metamod:Source version 1.10.7-dev

**Comment by akazetaa** [comment]
for the last error, should that line have the IsPlayerInGame(client) to verify it?

**Comment by rajkodev** [comment]
Hey @akazetaa, @olokos.
I'm issuing same problem, this is error that cause crash:

`L 04/15/2020 - 01:16:53: [SM] Exception reported: Failed to grow array
L 04/15/2020 - 01:16:53: [SM] Blaming: SurfTimer.smx
L 04/15/2020 - 01:16:53: [SM] Call stack trace:
L 04/15/2020 - 01:16:53: [SM] [0] PushArrayArray
L 04/15/2020 - 01:16:53: [SM] [1] Line 920, surftimer/replay.sp::RecordReplay
L 04/15/2020 - 01:16:53: [SM] [2] Line 1109, surftimer/hooks.sp::OnPlayerRunCmd`

Request to fix this error is posted long time ago on AM:
https://forums.alliedmods.net/showthread.php?t=260754&highlight=failed+grow+array

Thank you everyone for maintain this awesome mode!

**Comment by covertxd** [comment]
> Hey @akazetaa, @olokos.
> I'm issuing same problem, this is error that cause crash:
> 
> ```
> L 04/15/2020 - 01:16:53: [SM] Exception reported: Failed to grow array
> L 04/15/2020 - 01:16:53: [SM] Blaming: SurfTimer.smx
> L 04/15/2020 - 01:16:53: [SM] Call stack trace:
> L 04/15/2020 - 01:16:53: [SM] [0] PushArrayArray
> L 04/15/2020 - 01:16:53: [SM] [1] Line 920, surftimer/replay.sp::RecordReplay
> L 04/15/2020 - 01:16:53: [SM] [2] Line 1109, surftimer/hooks.sp::OnPlayerRunCmd
> ```
> 
> Request to fix this error is posted long time ago on AM:
> https://forums.alliedmods.net/showthread.php?t=260754&highlight=failed+grow+array
> 
> Thank you everyone for maintain this awesome mode!

The error occurs when the game engine runs out of memory, we are still investigating the cause of the memory leak.

**Comment by rajkodev** [comment]
@covertxd I also noticed when SQL server is running on same machine this error happens every 20+ hourse, but when database server is external problem is repeated every 4-5 hours.

**Comment by akazetaa** [comment]
any fix?

**Comment by sneak-it** [comment]
Your first issue (and what causes the out of memory crashes) has been fixed with 966ef60ab60affe1874fac28814a1caf34f0340b which is being tested on the dev branch with other fixes right now.

For the others, be patient.

**Comment by olokos** [comment]
@akazetaa 
Please try the recent 284 release and report back how it went for you.

From what I can tell all the issues you've had should be fixed already.

**Comment by akazetaa** [comment]
yeah i updated it when it was released, no crashes at the moment, i will keep an eye on it ^^

**Comment by olokos** [comment]
@akazetaa 
Glad to hear that! 
If you're not encountering the bugs you've mentioned anymore - please close this issue whenever you feel they are definitely gone already :wink:

**Comment by akazetaa** [comment]
seems like it is working fine, +50 maps played and no crashes at all, will open a new ticket if something happens, thanks =D
