### ISSUE TITLE
[BUG] Timer doesnt load

### ISSUE THREAD

**Issue by thorfriis** [olokos/Surftimer-olokos#24]
After i have compiled the plugins, and put them in /plugins, SM and all of its standard other plugins loads fine.

However SM doesnt even try to load Surftimer. It doesnt show up at all ingame, or in console/logs.

Have you experienced anything similar before?

**Comment by sneak-it** [comment]
What does it say in your sourcemod error logs? `/addons/sourcemod/logs/errors_*.log`

**Comment by thorfriis** [comment]
> L 04/17/2020 - 01:40:58: [SM] Unable to load extension "SteamWorks.ext": The specified module could not be found.


L 04/17/2020 - 01:40:58: [SM] Unable to load plugin "discord_api.smx": Required extension "SteamWorks" file("SteamWorks.ext") not running
L 04/17/2020 - 01:40:58: [SM] Unable to load plugin "SurfTimer.smx": Native "DiscordWebHook.Send" was not found

**Comment by sneak-it** [comment]
Please copy all extensions from the repo to your `/addons/sourcemod/extensions/` folder.

**Comment by thorfriis** [comment]
Hmmm... That should happen when i drag and dropped the whole repo into my server folder... But i can see it missed out on a couple extensions. I'll try again!

**Comment by thorfriis** [comment]
Hmmm... Stil same error

**Comment by covertxd** [comment]
What files are in your `addons/sourcemod/extensions` folder?

**Comment by thorfriis** [comment]
bintools.ext.dll
cleaner.autoload
cleaner.ext.2.csgo.dll
cleaner.ext.2.csgo.so
clientprefs.ext.dll
dbi.mysql.ext.dll
dbi.sqlite.ext.dll
dhooks.ext.dll
dhooks.ext.so
game.cstrike.ext.2.csgo.dll
game.cstrike.ext.2.css.dll
game.tf2.ext.2.tf2.dll
geoip.ext.dll
print.txt
regex.ext.dll
sdkhooks.ext.2.bgt.dll
sdkhooks.ext.2.blade.dll
sdkhooks.ext.2.bms.dll
sdkhooks.ext.2.contagion.dll
sdkhooks.ext.2.csgo.dll
sdkhooks.ext.2.css.dll
sdkhooks.ext.2.darkm.dll
sdkhooks.ext.2.dods.dll
sdkhooks.ext.2.doi.dll
sdkhooks.ext.2.ep1.dll
sdkhooks.ext.2.ep2.dll
sdkhooks.ext.2.eye.dll
sdkhooks.ext.2.hl2dm.dll
sdkhooks.ext.2.insurgency.dll
sdkhooks.ext.2.l4d.dll
sdkhooks.ext.2.l4d2.dll
sdkhooks.ext.2.nd.dll
sdkhooks.ext.2.sdk2013.dll
sdkhooks.ext.2.swarm.dll
sdkhooks.ext.2.tf2.dll
sdktools.ext.2.bgt.dll
sdktools.ext.2.blade.dll
sdktools.ext.2.bms.dll
sdktools.ext.2.contagion.dll
sdktools.ext.2.csgo.dll
sdktools.ext.2.css.dll
sdktools.ext.2.darkm.dll
sdktools.ext.2.dods.dll
sdktools.ext.2.doi.dll
sdktools.ext.2.ep1.dll
sdktools.ext.2.ep2.dll
sdktools.ext.2.eye.dll
sdktools.ext.2.hl2dm.dll
sdktools.ext.2.insurgency.dll
sdktools.ext.2.l4d.dll
sdktools.ext.2.l4d2.dll
sdktools.ext.2.nd.dll
sdktools.ext.2.sdk2013.dll
sdktools.ext.2.swarm.dll
sdktools.ext.2.tf2.dll
smjansson.ext.dll
smjansson.ext.so
SteamWorks.ext.so
topmenus.ext.dll
updater.ext.dll
webternet.ext.dll

**Comment by Bara** [comment]
You tried to load the linux versions on a windows server.

**Comment by thorfriis** [comment]
> You tried to load the linux versions on a windows server.

Of surftimer, or SM?

**Comment by Bara** [comment]
Extensions like smjansson and SteamWorks

**Comment by thorfriis** [comment]
> Extensions like smjansson and SteamWorks

Well, does the repo have a Windows version?

**Comment by covertxd** [comment]
http://users.alliedmods.net/~kyles/builds/SteamWorks/SteamWorks-git132-windows.zip

**Comment by thorfriis** [comment]
Oh well... This newbie keeps going.

Loaded but i get another error now.
Is my database wrongfully configured? 

```
L 04/17/2020 - 02:00:28: [SM] Exception reported: [SurfTimer] Database tables could not be created! Error: Unknown character set: 'utf8mb4'
L 04/17/2020 - 02:00:28: [SM] Blaming: SurfTimer.smx
L 04/17/2020 - 02:00:28: [SM] Call stack trace:
L 04/17/2020 - 02:00:28: [SM]   [0] SetFailState
L 04/17/2020 - 02:00:28: [SM]   [1] Line 118, surftimer/sql.sp::SQLTxn_CreateDatabaseFailed
```

**Comment by sneak-it** [comment]
What version is your MySQL server?

**Comment by thorfriis** [comment]
> What version is your MySQL server?

Maria DB 5.2.14

**Comment by Bara** [comment]
2013-01-30, pretty old. Would recommend an upgrade to 10.4 (latest stable version).

**Comment by thorfriis** [comment]
Thanks you everyone! It worked out in the end! 😄 
Dont know why i had downloaded an old mariadb service... I was the first to show up on google.

**Comment by olokos** [comment]
As a side note, always pay attention to the dates of the threads/guides you're following, that will help you avoid the problem in the future. :)

At least you will know that the links are most likely outdated.
