### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by samatazz** [olokos/Surftimer-olokos#27]
**Describe the bug**
when using !options and turning off sounds the sounds keep playing (e.g leaving zones and completing maps)
Menus are !options -> MISC -> Timer sounds

**Expected behavior**
the sounds should stop

**Screenshots**
self explanitory

**Plugin List**
N/A

**Additional context**
N/A

**Comment by qawery-just-sad** [comment]
repeated issue #3
