### ISSUE TITLE
[BUG] Pink and orange color tags are broken

### ISSUE THREAD

**Issue by samatazz** [olokos/Surftimer-olokos#30]
**Describe the bug**
colour pink and orange doesn't work

**Expected behavior**
pink and orange should work

**Screenshots**
https://cdn.discordapp.com/attachments/379572504542445568/700750818349023412/unknown.png

**Plugin List**
Shouldn't be

**Additional context**
N/A

**Comment by sneak-it** [comment]
Looks fine here, ensure all of your includes are up to date when compiling.
![](https://share.snksrv.com/i/uF8eX0.png)
