### ISSUE TITLE
[BUG] Changing teams when in a different style resets accel/velocity but not the style.

### ISSUE THREAD

**Issue by timyc** [olokos/Surftimer-olokos#34]
**Describe the bug**
Changing teams when in a different surfing style, such as low grav, resets any special velocity/acceleration changes applied but the style is still retained, allowing a player to complete the map with the style at a faster speed. Once a player respawns though (trigger teleported back to spawn), the style works as intended.

**Comment by FR33K1LL** [comment]
I am also getting this bug, when team is switched in low grav or slow mo , normal completion will result in time being set for that rank. How can I help with this issue? Im using release 285.

**Comment by LubricantJam** [comment]
I will take a look at the codebase later as I'm currently watching a TV series however if you'd like to attempt yourself then all you need to do is re-apply the settings for the style on PlayerSpawn.

**Comment by FR33K1LL** [comment]
No rush, enjoy your show. I would attempt to try that myself jam, unfortunately im not much of a coder.

**Comment by sneak-it** [comment]
[**@FR33K1LL**](https://github.com/FR33K1LL) commented on [May 9, 2020, 8:24 PM EDT](https://github.com/olokos/Surftimer-olokos/issues/34#issuecomment-626253792 "2020-05-10T00:24:20Z - Replied by Github Reply Comments"):
> No rush, enjoy your show. I would attempt to try that myself jam, unfortunately im not much of a coder.

Never too late to start learning! 😄

**Comment by FR33K1LL** [comment]
Lol for sure @sneak-it , im just trash at math. So that turns me off from coding, but I have taken a dive into the source pawn introduction article and it was alright.

**Comment by LubricantJam** [comment]
> Lol for sure @sneak-it , im just trash at math. So that turns me off from coding, but I have taken a dive into the source pawn introduction article and it was alright.

I am the worst at math and I code for a living so math really means nothing 😂

**Comment by FR33K1LL** [comment]
But all them algebraic functions lol

**Comment by LubricantJam** [comment]
> But all them algebraic functions lol

All that needs to be done is find the code that is set for the styles and pretty much copy and pasta into PlayerSpawn.

**Comment by FR33K1LL** [comment]
Ill give it a go

**Comment by LubricantJam** [comment]
Seems like it's already handled from this point down, are you sure you've tested on the latest branch? 

https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/hooks.sp#L99
