### ISSUE TITLE
[Suggestion] Option to render trails by proximity

### ISSUE THREAD

**Issue by timyc** [olokos/Surftimer-olokos#36]
**Is your feature request related to a problem? Please describe.**
When a lot of people have trails enabled, FPS drops occur for everyone. I think there's also an error that pops up on the side hud saying "Warning: Overflowed CClientRenderablesList group 0"

**Describe the solution you'd like**
Client-sided trail rendering (if that's what it's called) so trails only render for players when they're close to someone with the trail.

**Comment by sneak-it** [comment]
Chroma trails will be removed from the timer entirely soon. It is its own independent plugin and we do not want to support 3rd party plugins: https://github.com/Nickelony/Trails-Chroma

I would suggest possibly only offering them to certain group flags to help with this.

**Comment by 13ace37** [comment]
```cpp
gCV_CheapTrails = CreateConVar("sm_trails_cheap", "0", "Force cheap trails (FPS boost).", FCVAR_NOTIFY, true, 0.0, true, 1.0);
```
so you could simple change this cvar to 1
