### ISSUE TITLE
[BUG] Silent spec not working correctly

### ISSUE THREAD

**Issue by qawery-just-sad** [olokos/Surftimer-olokos#39]
**Describe the bug**
When spectating with silent spec enabled only other spectators don't see the one with silent spec but the person that is spectated sees everyone.

**Expected behavior**
Spectated person doesn't see the one with silent spec enabled.

**Screenshots**
What person spectated sees:
![sspechls](https://user-images.githubusercontent.com/53490397/79644239-e2a1d680-81a7-11ea-9c9d-50daf492ceb3.png)

What me with silent spec sees and what other spectators see:
![sspecme](https://user-images.githubusercontent.com/53490397/79644269-21d02780-81a8-11ea-8996-8a1d0196d0d9.png)

**Plugin List**
SurfTimer 281 master, SM1.10, MM1.10

**Additional context**
Maybe delete this function/command, not many people use it and it's a bit creepy.

**Comment by LubricantJam** [comment]
I have a commit that I can do to put silent spec in, I'll do it soon.
