### ISSUE TITLE
[BUG] NoJump-Zone

### ISSUE THREAD

**Issue by Deadt1me** [olokos/Surftimer-olokos#47]
The NoJump-Zone doesn't stop you from jumping.

I expected it to stop you from jumping or taking some other measures.

**Comment by 13ace37** [comment]
It does. Show me a ss of the zone pls

**Comment by Deadt1me** [comment]
![Download](https://user-images.githubusercontent.com/64086025/79878395-a9f33e80-83ed-11ea-8074-69f138c69c19.jpg)
![Download (1)](https://user-images.githubusercontent.com/64086025/79878398-aa8bd500-83ed-11ea-98d2-d39d117238df.jpg)
![Download (2)](https://user-images.githubusercontent.com/64086025/79878402-ab246b80-83ed-11ea-976b-da2276672565.jpg)
![Download (3)](https://user-images.githubusercontent.com/64086025/79878405-abbd0200-83ed-11ea-8b2e-3f2a6b10d380.jpg)

**Comment by 13ace37** [comment]
its not working in startzones

**Comment by Deadt1me** [comment]
I guess it's intentionally not working in Start-Zones?
I'll close this then, thanks!
