### ISSUE TITLE
[BUG] Chat colors are not displayed correctly

### ISSUE THREAD

**Issue by olokos** [olokos/Surftimer-olokos#49]
**Describe the bug**
Colors like {pink} are not displayed as colors, but as default color text. 

**Expected behavior**
{pink} should make text color pink

**Screenshots**
Surftimer color of text issue
[Gallery link](https://imgur.com/gallery/XvtGpOd) 
**Additional context**
This bug does not exist in release 274 from z4lab

**Comment by olokos** [comment]
This was an issue back in #30 
But I can confirm that I do have latest includes and I still encounter this bug. 
Not really sure why. 
@sneak-it 
Could you give your insight on this please?

**Comment by rajkodev** [comment]
Hey, to avoid additional BUG topics I will add here:

https://imgur.com/a/B7rLIkQ

**Comment by sashajov** [comment]
When I do !colors there are grey and grey2 colors, but in some even default ranks are gray and gray2. It should not be hard to fix, but I don't have an idea about broken pink, orange and lightblue. 🤡

**Comment by sashajov** [comment]
Hi. :)

@rajkodev and I recompiled the surftimer plugin with this **[colorvariables.inc](https://pastebin.com/fp32wdby)** and for us, working well.

SS Proof: https://i.imgur.com/zbmynJs.png

**Comment by breakthegreat** [comment]
Confirmed it worked by compiling with my version of colorvariables.inc
![image](https://user-images.githubusercontent.com/64219376/80128137-3bd08800-8563-11ea-9e68-e9674db2317e.png)

**Comment by olokos** [comment]
I just updated the repo, I am preparing my fork of colorvariables to apply recent fixes and one of my own! :)

**Comment by olokos** [comment]
So I have just forked the original ChatProcessor repo,merged any opened pull requests to chat-processor and applied missing colors needed for our plugin to work properly.

With his colorvariables.inc everything works properly and this issue is finally solved for good.

I hope nobody minds me putting my community link in the repository website?
