### ISSUE TITLE
Help needed Please

### ISSUE THREAD

**Issue by Kyli3Boi** [olokos/Surftimer-olokos#56]
Hi Everyone,

Im very very new to this so please take it easy on me. Im the process of creating a CS Go Surf server to learn and be educated however i am struggling. 

I have spent the better part of 30 hours trying to get this to work however i have not been at all successful. I am not able to get everything compiled without a ton of errors. Could i please have some assistance, i would appreciate it a lot.

//// chat-processor.sp
//
// chat-processor.sp(194) : error 017: undefined symbol "MAXLENGTH_FLAG"
// chat-processor.sp(194) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// chat-processor.sp(197) : error 130: cannot coerce functions to values
// chat-processor.sp(197) : error 163: indeterminate array size in "sizeof" expression (symbol "sFlag")
// chat-processor.sp(198) : error 130: cannot coerce functions to values
// chat-processor.sp(198) : error 163: indeterminate array size in "sizeof" expression (symbol "sFlag")
// chat-processor.sp(202) : error 017: undefined symbol "MAXLENGTH_BUFFER"
// chat-processor.sp(202) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// chat-processor.sp(203) : error 130: cannot coerce functions to values
// chat-processor.sp(203) : error 163: indeterminate array size in "sizeof" expression (symbol "sFormat")
// chat-processor.sp(265) : error 130: cannot coerce functions to values
// chat-processor.sp(282) : error 017: undefined symbol "MAXLENGTH_FLAG"
// chat-processor.sp(282) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// chat-processor.sp(283) : error 130: cannot coerce functions to values
// chat-processor.sp(283) : error 163: indeterminate array size in "sizeof" expression (symbol "sFlagCopy")
// chat-processor.sp(289) : error 130: cannot coerce functions to values
// chat-processor.sp(289) : error 163: indeterminate array size in "sizeof" expression (symbol "sFlag")
// chat-processor.sp(308) : error 130: cannot coerce functions to values
// chat-processor.sp(308) : error 163: indeterminate array size in "sizeof" expression (symbol "sFormat")
// chat-processor.sp(325) : error 130: cannot coerce functions to values
// chat-processor.sp(329) : error 130: cannot coerce functions to values
// chat-processor.sp(353) : error 017: undefined symbol "MAXLENGTH_FLAG"
// chat-processor.sp(353) : error 161: brackets after variable name indicate a fixed-size array, but a dynamic size was given - did you mean to use 'new char[size]' syntax?
// chat-processor.sp(354) : error 130: cannot coerce functions to values
// chat-processor.sp(354) : error 163: indeterminate array size in "sizeof" expression (symbol "sFlag")
// chat-processor.sp(359) : error 017: undefined symbol "MAXLENGTH_BUFFER"
//
// Compilation aborted.
// 26 Errors.

//// ckSurf-discord.sp
//
// ckSurf-discord.sp(68) : error 017: undefined symbol "Discord_EscapeString"
// ckSurf-discord.sp(68) : error 092: number of arguments does not match definition
// ckSurf-discord.sp(83) : error 017: undefined symbol "Discord_SendMessage"
// ckSurf-discord.sp(94) : error 017: undefined symbol "Discord_EscapeString"
// ckSurf-discord.sp(94) : error 092: number of arguments does not match definition
// ckSurf-discord.sp(114) : error 017: undefined symbol "Discord_SendMessage"
// ckSurf-discord.sp(124) : error 017: undefined symbol "Discord_EscapeString"
// ckSurf-discord.sp(124) : error 092: number of arguments does not match definition
// ckSurf-discord.sp(143) : error 017: undefined symbol "Discord_SendMessage"
//
// 9 Errors.

cp-scp-wrapper.sp
//
// E:\Surf Server\csgosl\server\csgo\addons\sourcemod\scripting\include\cp-scp-wrapper.inc(26) : error 181: function argument named 'recipients' differs from prototype
// E:\Surf Server\csgosl\server\csgo\addons\sourcemod\scripting\include\cp-scp-wrapper.inc(26) : error 181: function argument named 'name' differs from prototype
//
// 2 Errors.

get5.sp(25) : fatal error 183: cannot read from file: "json"
//
// Compilation aborted.
// 1 Error.

get5_apistats.sp
//
// get5_apistats.sp(32) : fatal error 183: cannot read from file: "json"
//
// Compilation aborted.
// 1 Error.

 multi1v1/natives.sp(85) : error 017: undefined symbol "Queue_Inside"
// multi1v1.sp(341) : error 017: undefined symbol "Queue_Init"
// multi1v1.sp(341) : warning 213: tag mismatch
// multi1v1.sp(398) : error 017: undefined symbol "Queue_Clear"
// multi1v1.sp(405) : error 017: undefined symbol "Queue_Enqueue"
// multi1v1.sp(426) : error 017: undefined symbol "Queue_Clear"
// multi1v1.sp(478) : error 017: undefined symbol "Queue_Drop"
// multi1v1.sp(538) : error 017: undefined symbol "Queue_Init"
// multi1v1.sp(538) : warning 213: tag mismatch
// multi1v1.sp(561) : error 017: undefined symbol "Queue_Init"
// multi1v1.sp(561) : warning 213: tag mismatch
// multi1v1.sp(562) : error 017: undefined symbol "Queue_Length"
// multi1v1.sp(564) : error 017: undefined symbol "Queue_Dequeue"
// multi1v1.sp(572) : error 017: undefined symbol "Queue_Length"
// multi1v1.sp(573) : error 017: undefined symbol "Queue_Dequeue"
// multi1v1.sp(577) : error 017: undefined symbol "Queue_Length"
// multi1v1.sp(597) : error 017: undefined symbol "Queue_Length"
// multi1v1.sp(604) : error 017: undefined symbol "Queue_Dequeue"
// multi1v1.sp(605) : error 017: undefined symbol "Queue_Dequeue"
// multi1v1.sp(626) : error 017: undefined symbol "Queue_Destroy"
// multi1v1.sp(665) : error 017: undefined symbol "Queue_Length"
// multi1v1.sp(666) : error 017: undefined symbol "Queue_Inside"
// multi1v1.sp(666) : warning 213: tag mismatch
// multi1v1.sp(669) : error 017: undefined symbol "Queue_Enqueue"
// multi1v1.sp(922) : error 017: undefined symbol "Queue_Enqueue"
// multi1v1.sp(1009) : error 017: undefined symbol "Queue_Enqueue"
// multi1v1.sp(1159) : error 017: undefined symbol "Queue_Length"
//
// 23 Errors.

retakes/natives.sp(32) : error 017: undefined symbol "Queue_Find"
// retakes/natives.sp(39) : error 017: undefined symbol "Queue_Find"
// retakes.sp(222) : error 017: undefined symbol "Queue_Init"
// retakes.sp(222) : warning 213: tag mismatch
// retakes.sp(238) : error 017: undefined symbol "PQ_Clear"
// retakes.sp(239) : error 017: undefined symbol "PQ_Clear"
// retakes.sp(283) : error 017: undefined symbol "Queue_Clear"
// retakes.sp(290) : error 017: undefined symbol "Queue_Enqueue"
// retakes.sp(320) : error 017: undefined symbol "Queue_Drop"
// retakes.sp(398) : error 017: undefined symbol "Queue_Drop"
// retakes.sp(424) : error 017: undefined symbol "Queue_Enqueue"
// retakes.sp(430) : error 017: undefined symbol "Queue_Enqueue"
// retakes.sp(684) : error 017: undefined symbol "PQ_Clear"
// retakes.sp(693) : warning 213: tag mismatch
// retakes.sp(697) : error 017: undefined symbol "Queue_IsEmpty"
// retakes.sp(698) : error 017: undefined symbol "Queue_Dequeue"
// retakes.sp(700) : warning 213: tag mismatch
// retakes.sp(707) : error 017: undefined symbol "PQ_Clear"
// retakes.sp(834) : error 017: undefined symbol "Queue_EnqueueFront"
// retakes.sp(844) : error 017: undefined symbol "Queue_Length"
//
// 17 Errors.

Any help would be fantastic. Thank you

**Comment by 13ace37** [comment]
> // multi1v1.sp(341) : error 017: undefined symbol "Queue_Init"

> // retakes.sp(222) : error 017: undefined symbol "Queue_Init"

doesn't look like a plugin for a surf server ^^

also never heard of any of the others except for the ck discord thingy.

**Comment by Kyli3Boi** [comment]
Hi, thanks for the reply.

Like i said im very very new to this, never done anything close to this before.

I was following this as best as i can https://github.com/olokos/Surftimer-olokos/blob/dev/README.md 

Clearly i have less of an idea of whats going on than i thought. Any pointers in the right direction?

**Comment by 13ace37** [comment]
You should skip the "compiling part" then and download this instead https://github.com/olokos/Surftimer-olokos/releases/tag/285

**Comment by Kyli3Boi** [comment]
Thanks, could you perhaps advise how i would "install" this correctly?

**Comment by breakthegreat** [comment]
Add me on discord i'll help! B r e a K#6625

**Comment by olokos** [comment]
Well, not really solved, seems like this isn't actually solving the problem with external calladmin conflicting with the one built in, but this issue has multiple issues based on outdated code, so I'll leave it closed.
