### ISSUE TITLE
[Suggestion] CP Showing units per second in chat

### ISSUE THREAD

**Issue by breakthegreat** [olokos/Surftimer-olokos#58]
**Describe the solution you'd like**
Seeing the speed in the chat as we pass checkpoint (same way its displayed for PR AND SR times)

**Additional context**
Just throwing a suggestion that was made by some people on my server long time ago :)

**Comment by LubricantJam** [comment]
And this suggestion is already in my PR.

**Comment by sneak-it** [comment]
Implemented with #59
