### ISSUE TITLE
[BUG] Unranked players have score 0 instead of -99999

### ISSUE THREAD

**Issue by KristianP26** [olokos/Surftimer-olokos#64]
Unranked players have score 0 instead of -99999
That bugging shorting in tab and when you want to spec highest player it set you on unranked.

**Comment by Bara** [comment]
#59 has a fix for this issue.

**Comment by Bara** [comment]
> Fixed issue where scoreboard would display Unranked players at the top of the scoreboard (if they had not yet been inserted into ck_playerrank) (Fixes #59).


#59 was merged, but this issue wasn't tagged correctly.
