### ISSUE TITLE
[BUG] I cant reach prespeed on ground 

### ISSUE THREAD

**Issue by KristianP26** [olokos/Surftimer-olokos#72]
This is example of pressped on ground.
https://www.youtube.com/watch?v=Ja7Fr01gHoI

I tryed it on olokos server and there it dont work too.
But i tryed it on aces and there it works.
It must be blocked by surftimer i tryed everything in my configuration.

**Comment by LubricantJam** [comment]
Nothing to do with the timer... Do some research and you'll find its to do with what movement unlocked you use.

**Comment by KristianP26** [comment]
Oh ok i dont use any movement unlocker that maybe why it dont work for me.
Can give me a recommendation for any ?

**Comment by LubricantJam** [comment]
> Oh ok i dont use any movement unlocker that maybe why it dont work for me.
> Can give me a recommendation for any ?

That would be exactly why... The ONLY movement unlocker you should use is attached to this post, I recommend installing this too.

https://github.com/jason-e/rngfix

**Comment by KristianP26** [comment]
Ok thanks lot.

**Comment by sneak-it** [comment]
> > Oh ok i dont use any movement unlocker that maybe why it dont work for me.
> > Can give me a recommendation for any ?
> 
> That would be exactly why... The ONLY movement unlocker you should use is attached to this repo and I recommend installing it too.
> 
> https://github.com/jason-e/rngfix

Where? What does RNGFix have to do with a movement unlocker?

**Comment by LubricantJam** [comment]
> > > Oh ok i dont use any movement unlocker that maybe why it dont work for me.
> > > Can give me a recommendation for any ?
> > 
> > 
> > That would be exactly why... The ONLY movement unlocker you should use is attached to this repo and I recommend installing it too.
> > https://github.com/jason-e/rngfix
> 
> Where? What does RNGFix have to do with a movement unlocker?

It doesn't silly, was recommending two things in one. Movement locker is included in the repo's README.
