### ISSUE TITLE
[BUG] New record will entirely crash the server and restart a new map

### ISSUE THREAD

**Issue by breakthegreat** [olokos/Surftimer-olokos#81]
**Describe the bug**
Once a new record is created, (when there is none before) it crashes the server

**Expected behavior**
Shouldn't crash the server

**Screenshots**

![image](https://user-images.githubusercontent.com/64219376/80559972-51074580-89ad-11ea-850c-687f3088bfbf.png)

**Comment by sneak-it** [comment]
Not a timer issue, you need to generate or inset a dummy nav file for the map so bots can join.

**Comment by breakthegreat** [comment]
the nav file isn't supposed to be created as someone join ?

**Comment by sneak-it** [comment]
No, the nav file is created as a bot joins.

**Comment by breakthegreat** [comment]
Alright that's weird because some maps won't even create .nav files and bots are working fine on it (sorry if im just being a genuine newbie but I'm trying to understand xd)

**Comment by sneak-it** [comment]
Some maps have nav files packed into the bsp, so they won't create an external navmesh file. There's a lot of info online in regards to this stuff, a search could provide more info than I can 😄

**Comment by breakthegreat** [comment]
Alright thanks for the help anyway :D
