### ISSUE TITLE
[BUG] Ranks points

### ISSUE THREAD

**Issue by edyedyy** [olokos/Surftimer-olokos#95]
**Describe the bug**
You have for example 3000 points what is Casual but you have 3000 points and you are New and the new rank is for 0 points
**Expected behavior**

**Screenshots**
https://imgur.com/a/PcqcFlp

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Additional context**
https://pastebin.com/61EEjALf
skillgroups.cfg

**Comment by KristianP26** [comment]
I think thats not a bug you just dont have range between ranks, like you have it in the first 2 ranks.
xxxx-xxxx

**Comment by KristianP26** [comment]
I thing if you type this "points" "7500" it will just give rank to player what have 7500 points.

**Comment by qawery-just-sad** [comment]
https://pastebin.com/WbM11t3E that will fix ur issue

**Comment by edyedyy** [comment]
dosen't work. players are in top3 and have the title [NEW] this cfg https://pastebin.com/Vxh0zmsS

**Comment by LubricantJam** [comment]
This isn't a timer issue, as said it's to do with your skill group ranges.

**Comment by TheGunter24** [comment]
are you set in the "default_titles" or something ?
you could also try this: https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/configs/surftimer/skillgroups.cfg to see if it is a problem with the config

**Comment by olokos** [comment]
Not a bug, so closing this.
