### ISSUE TITLE
[BUG] ThreadedSQL Branch upgrade bug

### ISSUE THREAD

**Issue by olokos** [olokos/Surftimer-olokos#97]
**Describe the bug**
Invoking
`sm_surtfimer_upgrade` or `sm_surftimer_migrate` doesn't work as expected
**Expected behavior**
The DB Should automatically update, especially 

**Screenshots**
![FirstCPUpgradeQueries](https://cdn.discordapp.com/attachments/704358653049962526/706618527330730025/unknown.png)
![BugPicture](https://media.discordapp.net/attachments/704358653049962526/706619136926547968/unknown.png)

![ThirdPhoto](https://image.prntscr.com/image/ddVNCricTJuTiwlbMRpOiA.png)

**Additional context**
I am reporting this bug on behalf of @KristianP26
I am yet to try the latest changes myself, life's been pretty hectic for me recently.

**Comment by Bara** [comment]
> sm_surftimer_upgrade
Starting database upgrade...
[SurfTimer] Upgrading database... (Version: 3)
surftimer | Database upgrade (Version 3) was successful

Version 3 upgrade runs fine on my test server. So I can't confirm it.

**Comment by Bara** [comment]
[SurfTimer.zip](https://github.com/olokos/Surftimer-olokos/files/4589027/SurfTimer.zip)
can you try it again with this smx file?

**Comment by KristianP26** [comment]
I will try it at night or tomorow morning and give you feedback.

**Comment by KristianP26** [comment]
@Bara so first i need to type sm_surtfimer_upgrade and after  sm_surftimer_migrate ?

**Comment by KristianP26** [comment]
Again same problem
![image](https://user-images.githubusercontent.com/28766334/81228551-8a176980-8fee-11ea-9fee-edfc69437673.png)
My DB Version: 10.1.44-MariaDB

**Comment by Bara** [comment]
Database upgrading should work now. [Test version](https://github.com/olokos/Surftimer-olokos/pull/71#issuecomment-624937989)

**Comment by olokos** [comment]
![Bug picture](https://cdn.discordapp.com/attachments/375452719529328644/707739740551643236/unknown.png)

This seems to happen currently, but going back to dev branch isn't a problem at all.

**Comment by olokos** [comment]
Fixed as of version 285.9 of threadedSQL
I hope you don't mind I'm just making versioning on your code @Bara ? 😅
